### ISSUE TITLE
Speedup padpo

### ISSUE THREAD

**Issue by Seluj78** [AFPy/padpo#55]
Padpo, on the `fake-docs` repository, takes about 5 minutes and a half to complete :/ How can it be sped up ?
https://github.com/PyDocTeur/fake-docs/pull/18/checks?check_run_id=1493393281

**Comment by Seluj78** [comment]
Maybe we could only run padpo (and other tests) on modified files ? (cc @JulienPalard)

**Comment by vpoulailleau** [comment]
With the old CI, `padpo` ran only on modified files, this was a huge performance boost.

But some profiling can be done to maybe identify a big issue to fix.

@JulienPalard @Seluj78 may be we can use the `-p` option of `padpo` with the number of the PR to check?

**Comment by JulienPalard** [comment]
https://github.com/python/python-docs-fr/pull/1500?
