### ISSUE TITLE
padpo doesn't like `*n*-uplet` on msgstr start

### ISSUE THREAD

**Issue by Seluj78** [AFPy/padpo#58]
As you can see, `*n*-uplet` is a valid word but padpo throws an error when it sees that word at the beginning of a translation

<img width="1292" alt="Screenshot 2021-01-28 at 13 33 28" src="https://user-images.githubusercontent.com/4641317/106139268-8247b880-616d-11eb-8d90-7923b329c6d5.png">
<img width="857" alt="Screenshot 2021-01-28 at 13 33 16" src="https://user-images.githubusercontent.com/4641317/106139274-84aa1280-616d-11eb-8103-f9e1a5aae986.png">

**Comment by vpoulailleau** [comment]
https://github.com/AFPy/padpo/blob/master/padpo/checkers/glossary.py needs to be updated, "n-uplet" was added to https://github.com/python/python-docs-fr/blob/3.9/CONTRIBUTING.rst

The entire file needs to be updated according to the sources in comment in the Python code.

**Comment by Seluj78** [comment]
Could you make a scrapper that auto does it ?

**Comment by vpoulailleau** [comment]
I have thought I could do it, but it was not feasible, because the glossary is not exhaustive (plural form…). This is a manual work, but in comment in the code, there is the exact commit from which comes the data, so that we can `git diff`

**Comment by Seluj78** [comment]
ah nice !

**Comment by vpoulailleau** [comment]
@Seluj78 C'est quoi l'astuce pour afficher les résultats padpo directement dans la pull request ?

**Comment by Seluj78** [comment]
@vpoulailleau aucune idée, ca l'a fait tout seul, je suppose que ton formatting l'a fait? ou alors c'est mes extensions ?

**Comment by vpoulailleau** [comment]
@Seluj78 Suite à une remarque de @JulienPalard, je respecte le formattage de GCC.

Je vois aussi les remarques de padpo dans la pull request. J'imagine qu'il a fallu configurer quelque chose dans le dépôt. Cela doit avoir un rapport avec https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md, non ?

**Comment by Seluj78** [comment]
Je n'ai aucune mémoire de configuration spécifique dans le répo, donc ça doit être par défaut et c'est déjà très stylé!
