### ISSUE TITLE
Suggestions automatiques 

### ISSUE THREAD

**Issue by Seluj78** [AFPy/padpo#6]
Ca serait ouf que padpo fasse des suggestions dans github automatiquement, en tant que bot même, sans avoir a le lancer (genre un cron ou un bot comme miss-illington)

**Comment by vpoulailleau** [comment]
Je serai ravi que ce soit le cas.

Comme je disais dans une autre issue, c'est raisonnablement facile de faire des commentaires automatique, c'est plus difficile de faire des suggestions. Ceci dit ça allègerait grandement le travail de relecture même si ce ne sont que des commentaires. Par contre des commentaires sans suggestions augmentent le travail du traducteur…

J'ai pas cherché, quelqu'un sait où est la doc pour faire un bot GitHub ?

**Comment by Seluj78** [comment]
Alors pour les suggestions c'est simple, c'est un commentaire avec un format particulier ;) pour un bot, je te conseille Mariatta, la maman des bots !

https://www.youtube.com/watch?v=Bs_mqDHvCUs&list=WL&index=2&t=0s

 https://github.com/Mariatta/

Son code est top

**Comment by vpoulailleau** [comment]
Je vais regarder ça à tête reposée ! :sleeping:

**Comment by Seluj78** [comment]
Je close, reopen si c'est toujours prévu ;)
