### ISSUE TITLE
Compat 3.12

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/padpo#68]
Hello Vincent,

Pitit souci padpo depuis la 3.12 :

```
$ padpo
Traceback (most recent call last):
  File "/home/mdk/src/python/python-docs-fr/.venv/bin/padpo", line 5, in <module>
    from padpo.padpo import main
  File "/home/mdk/src/python/python-docs-fr/.venv/lib/python3.12/site-packages/padpo/padpo.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by vpoulailleau** [comment]
@JulienPalard Ah oui !

Je voulais m'occuper de padpo et pygrammalecte pendant la PyConFR, mais c'est passé si vite !

Merci pour le signalement, je regarde dès que j'ai un peu de temps.

**Comment by vpoulailleau** [comment]
@JulienPalard Je viens de faire un padpo v0.12.0 qui contient la mise à jour de pygrammalecte, et le support de Python 3.9 à 3.12.

Faudra aussi mettre à jour poutils, mais je m'arrête là, j'ai faim :wink:
